# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 450))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{border-image:url(:/img/img_bg);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setMinimumSize(QtCore.QSize(150, 0))
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 0, 0, 1, 1)
        self.onlineButton = QtWidgets.QRadioButton(self.centralwidget)
        self.onlineButton.setMinimumSize(QtCore.QSize(150, 25))
        self.onlineButton.setStyleSheet("border-image: url(:/img/img_wh);")
        self.onlineButton.setObjectName("onlineButton")
        self.gridLayout.addWidget(self.onlineButton, 0, 1, 1, 1)
        self.webcamButton = QtWidgets.QRadioButton(self.centralwidget)
        self.webcamButton.setMinimumSize(QtCore.QSize(150, 25))
        self.webcamButton.setStyleSheet("border-image: url(:/img/img_wh);")
        self.webcamButton.setChecked(True)
        self.webcamButton.setObjectName("webcamButton")
        self.gridLayout.addWidget(self.webcamButton, 0, 2, 1, 1)
        self.offlineButton = QtWidgets.QRadioButton(self.centralwidget)
        self.offlineButton.setMinimumSize(QtCore.QSize(150, 25))
        self.offlineButton.setStyleSheet("border-image: url(:/img/img_wh);")
        self.offlineButton.setChecked(False)
        self.offlineButton.setObjectName("offlineButton")
        self.gridLayout.addWidget(self.offlineButton, 0, 3, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setEnabled(False)
        self.playButton.setMinimumSize(QtCore.QSize(150, 0))
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 0, 4, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 0))
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 0, 5, 1, 1)
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.videoLabel.sizePolicy().hasHeightForWidth())
        self.videoLabel.setSizePolicy(sizePolicy)
        self.videoLabel.setMinimumSize(QtCore.QSize(400, 400))
        self.videoLabel.setMaximumSize(QtCore.QSize(1000, 1000))
        self.videoLabel.setStyleSheet("border-image: url(:/img/img_bk);")
        self.videoLabel.setObjectName("videoLabel")
        self.gridLayout.addWidget(self.videoLabel, 1, 0, 1, 4)
        self.viewList = QtWidgets.QListWidget(self.centralwidget)
        self.viewList.setMinimumSize(QtCore.QSize(0, 400))
        self.viewList.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.viewList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewList.setStyleSheet("")
        self.viewList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.viewList.setAlternatingRowColors(False)
        self.viewList.setIconSize(QtCore.QSize(50, 50))
        self.viewList.setTextElideMode(QtCore.Qt.ElideRight)
        self.viewList.setMovement(QtWidgets.QListView.Static)
        self.viewList.setFlow(QtWidgets.QListView.TopToBottom)
        self.viewList.setProperty("isWrapping", False)
        self.viewList.setResizeMode(QtWidgets.QListView.Adjust)
        self.viewList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.viewList.setViewMode(QtWidgets.QListView.ListMode)
        self.viewList.setModelColumn(0)
        self.viewList.setUniformItemSizes(False)
        self.viewList.setWordWrap(False)
        self.viewList.setSelectionRectVisible(True)
        self.viewList.setObjectName("viewList")
        self.gridLayout.addWidget(self.viewList, 1, 4, 1, 2)
        self.infoList = QtWidgets.QListWidget(self.centralwidget)
        self.infoList.setMinimumSize(QtCore.QSize(0, 60))
        self.infoList.setMaximumSize(QtCore.QSize(16777215, 50))
        self.infoList.setObjectName("infoList")
        self.gridLayout.addWidget(self.infoList, 2, 0, 1, 6, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.viewList.setCurrentRow(-1)
        self.playButton.clicked.connect(MainWindow.switch_video)
        self.offlineButton.clicked.connect(MainWindow.chk_video_type)
        self.webcamButton.clicked.connect(MainWindow.chk_video_type)
        self.onlineButton.clicked.connect(MainWindow.chk_video_type)
        self.loadButton.clicked.connect(MainWindow.load_net_data_start)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "load net and data"))
        self.onlineButton.setText(_translate("MainWindow", "online"))
        self.webcamButton.setText(_translate("MainWindow", "webcam"))
        self.offlineButton.setText(_translate("MainWindow", "offline"))
        self.playButton.setText(_translate("MainWindow", "play"))
        self.stopButton.setText(_translate("MainWindow", "stop"))
        self.videoLabel.setText(_translate("MainWindow", "video"))
        self.viewList.setSortingEnabled(False)


import gui_source_rc
